### PR TITLE
Gitignore update

### PR DESCRIPTION
**Pull request by iambmelt**

### CODE REVIEW

**Comment by iambmelt** [comment]
```
Lint Report

Check performed at Wed Jul 15 09:14:48 PDT 2015.
6 errors and 29 warnings found:

Correctness
4   Error MissingPrefix: Missing Android XML namespace
2   Error NewApi: Calling new methods on older versions
1   Warning UnusedAttribute: Attribute unused on older versions
1   Warning GradleDependency: Obsolete Gradle Dependency
Performance
1   Warning UnusedResources: Unused resources
Bi-directional Text
9   Warning RtlSymmetry: Padding and margin symmetry
17  Warning RtlHardcoded: Using left/right instead of start/end attributes
Disabled Checks (11)

Correctness
MissingPrefix: Missing Android XML namespace
../../src/main/res/layout/fragment_user_details.xml:32: Unexpected namespace prefix "xmlns" found for tag RelativeLayout
  29 
  30         </LinearLayout>
  31 
  32         <RelativeLayout xmlns:tools="http://schemas.android.com/tools"
  33                         android:layout_width="match_parent"
  34                         android:layout_height="wrap_content"
../../src/main/res/layout/fragment_user_details.xml:196: Unexpected namespace prefix "xmlns" found for tag TextView
 193                 android:textAppearance="?android:attr/textAppearanceLarge"
 194                 android:id="@+id/managerSectionTitle"
 195                 android:text="@string/fragment_manager_title"
 196                 xmlns:android="http://schemas.android.com/apk/res/android"
 197                 android:layout_below="@+id/countryLabelTextView"/>
 198 
../../src/main/res/layout/fragment_user_details.xml:199: Unexpected namespace prefix "xmlns" found for tag LinearLayout
 196                 xmlns:android="http://schemas.android.com/apk/res/android"
 197                 android:layout_below="@+id/countryLabelTextView"/>
 198 
 199             <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
 200                           android:layout_width="match_parent"
 201                           android:layout_height="wrap_content"
../../src/main/res/layout/fragment_user_details.xml:220: Unexpected namespace prefix "xmlns" found for tag TextView
 217                       android:layout_height="wrap_content"
 218                       android:paddingLeft="?android:attr/listPreferredItemPaddingLeft"/>
 219 
 220                 <TextView xmlns:android="http://schemas.android.com/apk/res/android"
 221                       android:id="@+id/noManager"
 222                       android:textSize="16sp"
Note: This issue has an associated quickfix operation in Eclipse/ADT & Android Studio/IntelliJ Fix 
Priority: 6 / 10
Category: Correctness
Severity: Error
Explanation: Missing Android XML namespace.
Most Android views have attributes in the Android namespace. When referencing these attributes you must include the namespace prefix, or your attribute will be interpreted by aapt as just a custom attribute.

Similarly, in manifest files, nearly all attributes should be in the android: namespace.

More info:

To suppress this error, use the issue id "MissingPrefix" as explained in the Suppressing Warnings and Errors section.
NewApi: Calling new methods on older versions
../../src/main/java/com/microsoft/office365/profile/viewcontroller/BaseActivity.java:100: Call requires API level 21 (current min is 15): android.webkit.CookieManager#removeSessionCookies
  97 
  98             // Clear cookies
  99             if(Build.VERSION.SDK_INT >= 21){
 100                 CookieManager.getInstance().removeSessionCookies(null);
 101                 CookieManager.getInstance().flush();
 102             } else {
../../src/main/java/com/microsoft/office365/profile/viewcontroller/BaseActivity.java:101: Call requires API level 21 (current min is 15): android.webkit.CookieManager#flush
  98             // Clear cookies
  99             if(Build.VERSION.SDK_INT >= 21){
 100                 CookieManager.getInstance().removeSessionCookies(null);
 101                 CookieManager.getInstance().flush();
 102             } else {
 103                 CookieSyncManager.createInstance(this);
Note: This issue has an associated quickfix operation in Eclipse/ADT & Android Studio/IntelliJ Fix 
Priority: 6 / 10
Category: Correctness
Severity: Error
Explanation: Calling new methods on older versions.
This check scans through all the Android API calls in the application and warns about any calls that are not available on all versions targeted by this application (according to its minimum SDK attribute in the manifest).

If you really want to use this API and don't need to support older devices just set the minSdkVersion in your build.gradle or AndroidManifest.xml files.
If your code is deliberately accessing newer APIs, and you have ensured (e.g. with conditional execution) that this code will only ever be called on a supported platform, then you can annotate your class or method with the @TargetApi annotation specifying the local minimum SDK to apply, such as @TargetApi(11), such that this check considers 11 rather than your manifest file's minimum SDK as the required API level.

If you are deliberately setting android: attributes in style definitions, make sure you place this in a values-vNN folder in order to avoid running into runtime conflicts on certain devices where manufacturers have added custom attributes whose ids conflict with the new ones on later platforms.

Similarly, you can use tools:targetApi="11" in an XML file to indicate that the element will only be inflated in an adequate context.

More info:

To suppress this error, use the issue id "NewApi" as explained in the Suppressing Warnings and Errors section.
UnusedAttribute: Attribute unused on older versions
../../src/main/AndroidManifest.xml:28: Attribute parentActivityName is only used in API level 16 and higher (current min is 15)
  25             android:configChanges="keyboardHidden|orientation|screenSize"
  26             android:label="@string/app_name"
  27             android:noHistory="true"
  28             android:parentActivityName=".viewcontroller.UserDirectoryActivity" >
  29         </activity>
  30         <activity
Priority: 6 / 10
Category: Correctness
Severity: Warning
Explanation: Attribute unused on older versions.
This check finds attributes set in XML files that were introduced in a version newer than the oldest version targeted by your application (with the minSdkVersion attribute).

This is not an error; the application will simply ignore the attribute. However, if the attribute is important to the appearance of functionality of your application, you should consider finding an alternative way to achieve the same result with only available attributes, and then you can optionally create a copy of the layout in a layout-vNN folder which will be used on API NN or higher where you can take advantage of the newer attribute.

Note: This check does not only apply to attributes. For example, some tags can be unused too, such as the new <tag> element in layouts introduced in API 21.

More info:

To suppress this error, use the issue id "UnusedAttribute" as explained in the Suppressing Warnings and Errors section.
GradleDependency: Obsolete Gradle Dependency
../../build.gradle:24: A newer version of com.android.support:appcompat-v7 than 22.0.0 is available: 22.1.1
  21 
  22 dependencies {
  23     compile fileTree(dir: 'libs', include: ['*.jar'])
  24     compile 'com.android.support:appcompat-v7:22.0.0'
  25 
  26     // base OData library:
Note: This issue has an associated quickfix operation in Android Studio/IntelliJ Fix 
Priority: 4 / 10
Category: Correctness
Severity: Warning
Explanation: Obsolete Gradle Dependency.
This detector looks for usages of libraries where the version you are using is not the current stable release. Using older versions is fine, and there are cases where you deliberately want to stick with an older version. However, you may simply not be aware that a more recent version is available, and that is what this lint check helps find.

More info:

To suppress this error, use the issue id "GradleDependency" as explained in the Suppressing Warnings and Errors section.
Performance
UnusedResources: Unused resources
../../src/main/res/values/strings.xml:26: The resource R.string.malformed_url_toast_text appears to be unused
  23 
  24     <string name="auth_failure_toast_text">Error signing in\nCheck logcat for details</string>
  25     <string name="http_failure_toast_text">Error sending HTTP request\nCheck logcat for details</string>
  26     <string name="malformed_url_toast_text">The URL is malformed\nCheck logcat for details</string>
  27 
  28     <string name="empty_array_default_message">Not available</string>
Priority: 3 / 10
Category: Performance
Severity: Warning
Explanation: Unused resources.
Unused resources make applications larger and slow down builds.

More info:

To suppress this error, use the issue id "UnusedResources" as explained in the Suppressing Warnings and Errors section.
Bi-directional Text
RtlSymmetry: Padding and margin symmetry
../../src/main/res/layout/fragment_user_details.xml:58: When you define paddingRight you should probably also define paddingLeft for right-to-left symmetry
  55                 android:id="@+id/jobTitleLabelTextView"
  56                 android:layout_below="@+id/thumbnailPhotoImageView"
  57                 android:layout_alignRight="@+id/departmentLabelTextView"
  58                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  59 
  60             <TextView
../../src/main/res/layout/fragment_user_details.xml:78: When you define paddingRight you should probably also define paddingLeft for right-to-left symmetry
  75                 android:id="@+id/hireDateLabelTextView"
  76                 android:layout_below="@+id/departmentLabelTextView"
  77                 android:layout_alignRight="@+id/departmentLabelTextView"
  78                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  79 
  80             <TextView
../../src/main/res/layout/fragment_user_details.xml:88: When you define paddingRight you should probably also define paddingLeft for right-to-left symmetry
  85                 android:id="@+id/aliasLabelTextView"
  86                 android:layout_below="@+id/hireDateLabelTextView"
  87                 android:layout_alignRight="@+id/departmentLabelTextView"
  88                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  89 
  90             <TextView
../../src/main/res/layout/fragment_user_details.xml:98: When you define paddingRight you should probably also define paddingLeft for right-to-left symmetry
  95                 android:id="@+id/telephoneNumberLabelTextView"
  96                 android:layout_below="@+id/aliasLabelTextView"
  97                 android:layout_alignRight="@+id/departmentLabelTextView"
  98                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  99 
 100             <TextView
../../src/main/res/layout/fragment_user_details.xml:108: When you define paddingRight you should probably also define paddingLeft for right-to-left symmetry
 105                 android:id="@+id/stateLabelTextView"
 106                 android:layout_below="@+id/telephoneNumberLabelTextView"
 107                 android:layout_alignRight="@+id/departmentLabelTextView"
 108                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
 109 
 110             <TextView
+ 4 More Occurrences...
Priority: 6 / 10
Category: Bi-directional Text
Severity: Warning
Explanation: Padding and margin symmetry.
If you specify padding or margin on the left side of a layout, you should probably also specify padding on the right side (and vice versa) for right-to-left layout symmetry.

More info:

To suppress this error, use the issue id "RtlSymmetry" as explained in the Suppressing Warnings and Errors section.
RtlHardcoded: Using left/right instead of start/end attributes
../../src/main/res/layout/fragment_user_details.xml:57: Consider adding android:layout_alignEnd="@+id/departmentLabelTextView" to better support right-to-left layouts
  54                 android:text="@string/fragment_general_job_title_label"
  55                 android:id="@+id/jobTitleLabelTextView"
  56                 android:layout_below="@+id/thumbnailPhotoImageView"
  57                 android:layout_alignRight="@+id/departmentLabelTextView"
  58                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  59 
../../src/main/res/layout/fragment_user_details.xml:58: Consider adding android:paddingEnd="?android:attr/listPreferredItemPaddingRight" to better support right-to-left layouts
  55                 android:id="@+id/jobTitleLabelTextView"
  56                 android:layout_below="@+id/thumbnailPhotoImageView"
  57                 android:layout_alignRight="@+id/departmentLabelTextView"
  58                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  59 
  60             <TextView
../../src/main/res/layout/fragment_user_details.xml:67: Consider adding android:paddingStart="?android:attr/listPreferredItemPaddingLeft" to better support right-to-left layouts
  64                 android:text="@string/fragment_general_department_label"
  65                 android:id="@+id/departmentLabelTextView"
  66                 android:layout_below="@+id/jobTitleLabelTextView"
  67                 android:paddingLeft="?android:attr/listPreferredItemPaddingLeft"
  68                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  69 
../../src/main/res/layout/fragment_user_details.xml:68: Consider adding android:paddingEnd="?android:attr/listPreferredItemPaddingRight" to better support right-to-left layouts
  65                 android:id="@+id/departmentLabelTextView"
  66                 android:layout_below="@+id/jobTitleLabelTextView"
  67                 android:paddingLeft="?android:attr/listPreferredItemPaddingLeft"
  68                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  69 
  70             <TextView
../../src/main/res/layout/fragment_user_details.xml:77: Consider adding android:layout_alignEnd="@+id/departmentLabelTextView" to better support right-to-left layouts
  74                 android:text="@string/fragment_general_hire_date_label"
  75                 android:id="@+id/hireDateLabelTextView"
  76                 android:layout_below="@+id/departmentLabelTextView"
  77                 android:layout_alignRight="@+id/departmentLabelTextView"
  78                 android:paddingRight="?android:attr/listPreferredItemPaddingRight"/>
  79 
+ 12 More Occurrences...
Priority: 5 / 10
Category: Bi-directional Text
Severity: Warning
Explanation: Using left/right instead of start/end attributes.
Using Gravity#LEFT and Gravity#RIGHT can lead to problems when a layout is rendered in locales where text flows from right to left. Use Gravity#START and Gravity#END instead. Similarly, in XML gravity and layout_gravity attributes, use start rather than left.
For XML attributes such as paddingLeft and layout_marginLeft, use paddingStart and layout_marginStart. NOTE: If your minSdkVersion is less than 17, you should add both the older left/right attributes as well as the new start/right attributes. On older platforms, where RTL is not supported and the start/right attributes are unknown and therefore ignored, you need the older left/right attributes. There is a separate lint check which catches that type of error.
(Note: For Gravity#LEFT and Gravity#START, you can use these constants even when targeting older platforms, because the start bitmask is a superset of the left bitmask. Therefore, you can use gravity="start" rather than gravity="left|start".)

More info:

To suppress this error, use the issue id "RtlHardcoded" as explained in the Suppressing Warnings and Errors section.
Disabled Checks
The following issues were not run by lint, either because the check is not enabled by default, or because it was disabled with a command line flag or via one or more lint.xml configuration files in the project directories. 

BackButton
Disabled By: Default
Priority: 6 / 10
Category: Usability
Severity: Warning
Explanation: Back button.
According to the Android Design Guide,

"Other platforms use an explicit back button with label to allow the user to navigate up the application's hierarchy. Instead, Android uses the main action bar's app icon for hierarchical navigation and the navigation bar's back button for temporal navigation."
This check is not very sophisticated (it just looks for buttons with the label "Back"), so it is disabled by default to not trigger on common scenarios like pairs of Back/Next buttons to paginate through screens.

More info: http://developer.android.com/design/patterns/pure-android.html

To suppress this error, use the issue id "BackButton" as explained in the Suppressing Warnings and Errors section.
EasterEgg
Disabled By: Default
Priority: 6 / 10
Category: Security
Severity: Warning
Explanation: Code contains easter egg.
An "easter egg" is code deliberately hidden in the code, both from potential users and even from other developers. This lint check looks for code which looks like it may be hidden from sight.

More info:

To suppress this error, use the issue id "EasterEgg" as explained in the Suppressing Warnings and Errors section.
FieldGetter
Disabled By: Default
Priority: 4 / 10
Category: Performance
Severity: Warning
Explanation: Using getter instead of field.
Accessing a field within the class that defines a getter for that field is at least 3 times faster than calling the getter. For simple getters that do nothing other than return the field, you might want to just reference the local field directly instead.

NOTE: As of Android 2.3 (Gingerbread), this optimization is performed automatically by Dalvik, so there is no need to change your code; this is only relevant if you are targeting older versions of Android.

More info: http://developer.android.com/guide/practices/design/performance.html#internal_get_set

To suppress this error, use the issue id "FieldGetter" as explained in the Suppressing Warnings and Errors section.
IconExpectedSize
Disabled By: Default
Priority: 5 / 10
Category: Usability:Icons
Severity: Warning
Explanation: Icon has incorrect size.
There are predefined sizes (for each density) for launcher icons. You should follow these conventions to make sure your icons fit in with the overall look of the platform.

More info: http://developer.android.com/design/style/iconography.html

To suppress this error, use the issue id "IconExpectedSize" as explained in the Suppressing Warnings and Errors section.
LogConditional
Disabled By: Default
Priority: 5 / 10
Category: Performance
Severity: Warning
Explanation: Unconditional Logging Calls.
The BuildConfig class (available in Tools 17) provides a constant, "DEBUG", which indicates whether the code is being built in release mode or in debug mode. In release mode, you typically want to strip out all the logging calls. Since the compiler will automatically remove all code which is inside a "if (false)" check, surrounding your logging calls with a check for BuildConfig.DEBUG is a good idea.

If you really intend for the logging to be present in release mode, you can suppress this warning with a @SuppressLint annotation for the intentional logging calls.

More info:

To suppress this error, use the issue id "LogConditional" as explained in the Suppressing Warnings and Errors section.
NegativeMargin
Disabled By: Default
Priority: 4 / 10
Category: Usability
Severity: Warning
Explanation: Negative Margins.
Margin values should be positive. Negative values are generally a sign that you are making assumptions about views surrounding the current one, or may be tempted to turn off child clipping to allow a view to escape its parent. Turning off child clipping to do this not only leads to poor graphical performance, it also results in wrong touch event handling since touch events are based strictly on a chain of parent-rect hit tests. Finally, making assumptions about the size of strings can lead to localization problems.

More info:

To suppress this error, use the issue id "NegativeMargin" as explained in the Suppressing Warnings and Errors section.
NewerVersionAvailable
Note: This issue has an associated quickfix operation in Android Studio/IntelliJ Fix 
Disabled By: Default
Priority: 4 / 10
Category: Correctness
Severity: Warning
Explanation: Newer Library Versions Available.
This detector checks with a central repository to see if there are newer versions available for the dependencies used by this project.
This is similar to the GradleDependency check, which checks for newer versions available in the Android SDK tools and libraries, but this works with any MavenCentral dependency, and connects to the library every time, which makes it more flexible but also much slower.

More info:

To suppress this error, use the issue id "NewerVersionAvailable" as explained in the Suppressing Warnings and Errors section.
SelectableText
Note: This issue has an associated quickfix operation in Android Studio/IntelliJ Fix 
Disabled By: Default
Priority: 7 / 10
Category: Usability
Severity: Warning
Explanation: Dynamic text should probably be selectable.
If a <TextView> is used to display data, the user might want to copy that data and paste it elsewhere. To allow this, the <TextView> should specify android:textIsSelectable="true".

This lint check looks for TextViews which are likely to be displaying data: views whose text is set dynamically. This value will be ignored on platforms older than API 11, so it is okay to set it regardless of your minSdkVersion.

More info:

To suppress this error, use the issue id "SelectableText" as explained in the Suppressing Warnings and Errors section.
StopShip
Note: This issue has an associated quickfix operation in Android Studio/IntelliJ Fix 
Disabled By: Default
Priority: 10 / 10
Category: Correctness
Severity: Warning
Explanation: Code contains STOPSHIP marker.
Using the comment // STOPSHIP can be used to flag code that is incomplete but checked in. This comment marker can be used to indicate that the code should not be shipped until the issue is addressed, and lint will look for these.

More info:

To suppress this error, use the issue id "StopShip" as explained in the Suppressing Warnings and Errors section.
TypographyQuotes
Note: This issue has an associated quickfix operation in Eclipse/ADT & Android Studio/IntelliJ Fix 
Disabled By: Default
Priority: 5 / 10
Category: Usability:Typography
Severity: Warning
Explanation: Straight quotes can be replaced with curvy quotes.
Straight single quotes and double quotes, when used as a pair, can be replaced by "curvy quotes" (or directional quotes). This can make the text more readable.

Note that you should never use grave accents and apostrophes to quote, `like this'.

(Also note that you should not use curvy quotes for code fragments.)

More info: http://en.wikipedia.org/wiki/Quotation_mark

To suppress this error, use the issue id "TypographyQuotes" as explained in the Suppressing Warnings and Errors section.
UnusedIds
Disabled By: Default
Priority: 1 / 10
Category: Performance
Severity: Warning
Explanation: Unused id.
This resource id definition appears not to be needed since it is not referenced from anywhere. Having id definitions, even if unused, is not necessarily a bad idea since they make working on layouts and menus easier, so there is not a strong reason to delete these.

More info:

To suppress this error, use the issue id "UnusedIds" as explained in the Suppressing Warnings and Errors section.
Suppressing Warnings and Errors
Lint errors can be suppressed in a variety of ways:

1. With a @SuppressLint annotation in the Java code
2. With a tools:ignore attribute in the XML file
3. With ignore flags specified in the build.gradle file, as explained below
4. With a lint.xml configuration file in the project
5. With a lint.xml configuration file passed to lint via the --config flag
6. With the --ignore flag passed to lint.

To suppress a lint warning with an annotation, add a @SuppressLint("id") annotation on the class, method or variable declaration closest to the warning instance you want to disable. The id can be one or more issue id's, such as "UnusedResources" or {"UnusedResources","UnusedIds"}, or it can be "all" to suppress all lint warnings in the given scope.

To suppress a lint warning in an XML file, add a tools:ignore="id" attribute on the element containing the error, or one of its surrounding elements. You also need to define the namespace for the tools prefix on the root element in your document, next to the xmlns:android declaration:
xmlns:tools="http://schemas.android.com/tools"

To suppress a lint warning in a build.gradle file, add a section like this:

android {
    lintOptions {
        disable 'TypographyFractions','TypographyQuotes'
    }
}

Here we specify a comma separated list of issue id's after the disable command. You can also use warning or error instead of disable to change the severity of issues.

To suppress lint warnings with a configuration XML file, create a file named lint.xml and place it at the root directory of the project in which it applies.

The format of the lint.xml file is something like the following:

<?xml version="1.0" encoding="UTF-8"?>
<lint>
    <!-- Disable this given check in this project -->
    <issue id="IconMissingDensityFolder" severity="ignore" />

    <!-- Ignore the ObsoleteLayoutParam issue in the given files -->
    <issue id="ObsoleteLayoutParam">
        <ignore path="res/layout/activation.xml" />
        <ignore path="res/layout-xlarge/activation.xml" />
    </issue>

    <!-- Ignore the UselessLeaf issue in the given file -->
    <issue id="UselessLeaf">
        <ignore path="res/layout/main.xml" />
    </issue>

    <!-- Change the severity of hardcoded strings to "error" -->
    <issue id="HardcodedText" severity="error" />
</lint>

To suppress lint checks from the command line, pass the --ignore flag with a comma separated list of ids to be suppressed, such as:
$ lint --ignore UnusedResources,UselessLeaf /my/project/path

For more information, see http://tools.android.com/tips/lint/suppressing-lint-warnings
```

**Comment by iambmelt** [comment]
```
:app:clean UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72200Library
:app:prepareComAndroidSupportSupportV42211Library
:app:prepareComMicrosoftAadAdal112Library
:app:prepareComMicrosoftServicesOdataEngineAndroidImpl0130Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
AAPT warning(Job{title=Cruncher abc_spinner_mtrl_am_alpha.9.png, latch=BooleanLatch{signaled=false}, result=false}): /Users/brianmel/Desktop/test/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:compileDebugJavaNote: /Users/brianmel/Desktop/test/app/src/main/java/com/microsoft/office365/profile/viewcontroller/BaseActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/brianmel/Desktop/test/app/src/main/java/com/microsoft/office365/profile/util/AuthenticationManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:app:preDexDebug
:app:dexDebug
:app:processDebugJavaRes UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug
:app:checkReleaseManifest
:app:prepareReleaseDependencies
:app:compileReleaseAidl
:app:compileReleaseRenderscript
:app:generateReleaseBuildConfig
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets
:app:generateReleaseResValues
:app:generateReleaseResources
:app:mergeReleaseResources
AAPT warning(Job{title=Cruncher abc_spinner_mtrl_am_alpha.9.png, latch=BooleanLatch{signaled=false}, result=false}): /Users/brianmel/Desktop/test/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Process list not empty
:app:processReleaseManifest
:app:processReleaseResources
:app:generateReleaseSources
:app:compileReleaseJavaNote: /Users/brianmel/Desktop/test/app/src/main/java/com/microsoft/office365/profile/viewcontroller/BaseActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/brianmel/Desktop/test/app/src/main/java/com/microsoft/office365/profile/util/AuthenticationManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:app:lintVitalRelease SKIPPED
:app:compileReleaseNdk UP-TO-DATE
:app:preDexRelease
:app:dexRelease
:app:processReleaseJavaRes UP-TO-DATE
:app:packageRelease
:app:assembleRelease
:app:assemble
:app:compileLint
:app:lint
Ran lint on variant debug: 35 issues found
Ran lint on variant release: 35 issues found
Wrote HTML report to file:/Users/brianmel/Desktop/test/app/build/outputs/lint-results.html
Wrote XML report to /Users/brianmel/Desktop/test/app/build/outputs/lint-results.xml
:app:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 32.584 secs
```

**Comment by iambmelt** [comment]
Steps to repro:

`git clone https://github.com/OfficeDev/O365-Android-Profile.git .; gradle clean build`

**Comment by ricalo** [comment]
Got it. I'll look into this later

**Pull request merged**
